version: '3'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      GUILD_ID: ${GUILD_ID}
      ALLOWED_ROLES: ${ALLOWED_ROLES}
      CATEGORY_NAME: ${CATEGORY_NAME}
      THUMBNAIL_URL: ${THUMBNAIL_URL}
